name: Deploy Frontend to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  DOCKERHUB_REPO: sohampa/php-frontend-laravel
  ECS_CLUSTER: soham-php-laravel-app
  ECS_SERVICE: soham-php-laravel-fet-service
  ECS_TASK_FAMILY: soham-php-laravel-fet
  REACT_APP_API_URL: http://100.26.224.35:8000

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        run: |
          IMAGE=${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          docker build --build-arg REACT_APP_API_URL=${{ env.REACT_APP_API_URL }} -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Render ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: soham-php-laravel-fet-revision.json  # base JSON stored in repo
          container-name: php-laravel-fet          # must match ECS container name
          image: ${{ env.IMAGE }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
