name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  DOCKERHUB_REPO: sohampa/php-frontend-laravel
  IMAGE_TAG: v3   # ✅ Fixed tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push image
      - name: Build and Push Docker Image
        run: |
          echo "Building image: ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}"

          docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            -t ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }} .

          docker push ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}

      # (Optional) Tag as "latest"
      - name: Tag as latest
        run: |
          docker tag ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }} ${{ env.DOCKERHUB_REPO }}:latest
          docker push ${{ env.DOCKERHUB_REPO }}:latest
